dataset_params:
  im_path: '../Dataset'  # Path to the dataset folder
  im_channels: 3
  im_size: 256
  name: 'sar'
  # Data splitting parameters
  train_split: 0.7
  val_split: 0.15
  test_split: 0.15

diffusion_params:
  num_timesteps: 1000
  beta_start: 0.00085
  beta_end: 0.012

ldm_params:
  down_channels: [512, 768, 1024, 1280]
  mid_channels: [1280, 1024, 768]
  down_sample: [True, True, True]
  attn_down: [False, True, True, True]
  time_emb_dim: 768
  norm_channels: 32
  num_heads: 16
  conv_out_channels: 256
  num_down_layers: 3
  num_mid_layers: 4
  num_up_layers: 3
  condition_config:
    condition_types: ['text', 'image']
    text_condition_config:
      text_embed_model: 'clip'  # or 'bert'
      train_text_embed_model: False
      text_embed_dim: 512
      cond_drop_prob: 0.1
    image_condition_config:
      image_condition_input_channels: 3  # SAR images converted to RGB
      image_condition_output_channels: 3
      image_condition_h: 256
      image_condition_w: 256
      cond_drop_prob: 0.05

autoencoder_params:
  z_channels: 8
  codebook_size: 16384
  down_channels: [128, 256, 512, 768]
  mid_channels: [768, 768, 512]
  down_sample: [True, True, True]
  attn_down: [False, True, False]
  norm_channels: 32
  num_heads: 8
  num_down_layers: 3
  num_mid_layers: 3
  num_up_layers: 2

train_params:
  seed: 42
  task_name: 'sar_colorization'
  ldm_batch_size: 16
  autoencoder_batch_size: 16
  disc_start: 2000
  disc_weight: 0.5
  codebook_weight: 1
  commitment_beta: 0.2
  perceptual_weight: 0.1
  kl_weight: 0.000005
  ldm_epochs: 70
  autoencoder_epochs: 25
  num_samples: 4
  num_grid_rows: 2
  ldm_lr: 1e-4
  autoencoder_lr: 0.00001
  autoencoder_acc_steps: 4
  autoencoder_img_save_steps: 64
  save_latents: True  # Enable for faster training after autoencoder is trained
  cf_guidance_scale: 7.5  # Classifier-free guidance scale
  vae_latent_dir_name: 'vae_latents'
  vqvae_latent_dir_name: 'vqvae_latents'
  ldm_ckpt_name: 'ddpm_ckpt_sar_text_image_cond.pth'
  vqvae_autoencoder_ckpt_name: 'vqvae_autoencoder_ckpt.pth'
  vae_autoencoder_ckpt_name: 'vae_autoencoder_ckpt.pth'
  vqvae_discriminator_ckpt_name: 'vqvae_discriminator_ckpt.pth'
  vae_discriminator_ckpt_name: 'vae_discriminator_ckpt.pth'
